### ISSUE TITLE
not working with jhipster 3.1.0

### ISSUE THREAD

**Issue by faresyusuf** [moifort/generator-jhipster-google-maps#5]
Hi there,
probably the generator-jhipster-google-maps is not working with current version of jhipster. here is the error log, 
# ps, i have provided the api key.

(1/1) What is your google API key? 
Composing JHipster configuration with module google-maps
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.addAngularJsConfig is not a function
    at module.exports.yeoman.generators.Base.extend.writing (/usr/lib/node_modules/generator-jhipster-google-maps/generators/app/index.js:73:22)
    at /usr/lib/node_modules/generator-jhipster-google-maps/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by moifort** [comment]
Indeed, it's because the generator is not updated for the new Jhipster version, I will make the update soon! Or if you want you can make a pull request too!

**Comment by johnosorio** [comment]
+1

**Comment by DevOpsEngineer** [comment]
Issue still persists. I am using JHipster Generator v3.5.1 and getting the exact message once I place my Google API key. Please advise.

**Comment by theguehu** [comment]
Hello
have there been any update on this particular issue?

**Comment by gitrekm** [comment]
Hello

I have exactly the same Issue. I'm using Jhipster 3.10.0

Thanks in advance for support

**Comment by pascalgrimaud** [comment]
This module need to be updated and is not compatible with JHipster 3+.
I'm not sure Thibault is available to update it.
So PR is really welcome!

**Comment by cartsofware** [comment]
+1

**Comment by pascalgrimaud** [comment]
Should be fixed by https://github.com/moifort/generator-jhipster-google-maps/pull/7
